In [1]:
import pandas as pd
import altair as alt
import os
import re
import numpy as np

analysis_date = "260408"

In [ ]:
# CSV file available upon request
df = pd.read_csv("data/raw_respondent_data.csv")
df = df[df['Finished'] == 'True']

condition_name_mapping = {
    'treatment_recommendation': 'Recommended Treatment',
    'best_options': 'Options to Consider',
    'worst_options': 'Options to Avoid',
}

df['AIInterface'] = df['AIInterface'].replace(condition_name_mapping)
df

In [3]:
df['Q17.1'].value_counts()

Q17.1
Yes, I'll review two additional cases    143
No, take me to the final questions        84
Name: count, dtype: int64

## Process Respondent-Level Data

In [4]:
# Clean demographic columns
df['practice_setting'] = df['practice_setting'].replace({
    'Academic, university aﬃliated': 'Academic, university affiliated',
    'Academic, not university aﬃliated': 'Academic, not university affiliated'
})
df['specialty'] = df['specialty'].where(~df['specialty'].str.startswith('Other'), 'Other')
df['clinical_time'] = df['clinical_time'].replace({
    'More than 50% but less than 95%': 'Majority',
    'Less than 50%': 'Minority',
    'All or almost all (95% or more)': 'Full',
})
df['Duration (in seconds)'] = df['Duration (in seconds)'].astype(float)

In [5]:
perception_cols = ['Productivity',
    'Effectiveness',
    'EaseOfUse',
    'HighOutputQuality',
    'WouldUse']
df = df.rename(columns={
    'Q3.2': 'Experience',
    'Q3.3': 'SepsisExpertise',
    'Q18.2_1': 'Productivity',
    'Q18.2_2': 'Effectiveness',
    'Q18.2_3': 'EaseOfUse',
    'Q18.2_4': 'HighOutputQuality',
    'Q18.2_5': 'WouldUse',
    'Q18.4': 'UsefulnessFreeText',
    'Q18.5': 'IdealAIRoleFreeText',
    'Q18.6': 'FeedbackFreeText',
})
df[perception_cols] = df[perception_cols].replace({
    'Strongly disagree': 1, 'Disagree': 2, 'Somewhat disagree': 3, 'Neither agree nor disagree': 4,
    'Somewhat agree': 5, 'Agree': 6, 'Strongly agree': 7
})
    
df['Total Satisfaction'] = df[perception_cols].sum(axis=1)

/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/295012698.py:18: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[perception_cols] = df[perception_cols].replace({

In [6]:
print(df['specialty'].value_counts())
print(df['specialty_10_TEXT'].value_counts())
print(df['clinical_time'].value_counts())
print(df['practice_setting'].value_counts())
print(df['Experience'].value_counts())
print(df['SepsisExpertise'].value_counts())

specialty
Internal medicine, pulmonary        160
Internal medicine, not pulmonary     16
Anesthesiology                       15
Emergency medicine                   14
Other                                14
Surgery                               8
Neurology                             1
Name: count, dtype: int64
specialty_10_TEXT
Critical Care Medicine                         1
pulmonary and critical care fellow             1
Emergency and internal medicine                1
Internal Medicine-Pediatrics                   1
Pulmonary/Critical Care                        1
Pulmonary Critical Care                        1
Critical Care                                  1
Ob/gyn                                         1
critical care medicine/ infectious diseases    1
Internal Medicine, Critical Care               1
Critical care and nephrology                   1
Name: count, dtype: int64
clinical_time
Minority    87
Majority    76
Full        62
Name: count, dtype: int64
practice_setting
Academic, university affiliated        175
Community                               27
Academic, not university affiliated     24
Other                                    2
Name: count, dtype: int64
Experience
> 10 years    178
5-10 years     39
3-5 years      10
< 1 year        1
Name: count, dtype: int64
SepsisExpertise
Proficient - deep understanding                      105
Expert - authoritative knowledge                     105
Competent - good working and background knowledge     18
Name: count, dtype: int64

In [7]:
# Clean multiple choice demographics
df['Experience'] = df['Experience'].replace({
    '< 1 year': 1,
    '1-2 years': 2,
    '3-5 years': 3,
    '5-10 years': 4,
    '> 10 years': 5
})
df['SepsisExpertise'] = df['SepsisExpertise'].replace({
    'Novice - no experience': 1,
    'Beginner - some working knowledge': 2,
    'Competent - good working and background knowledge': 3,
    'Proficient - deep understanding': 4,
    'Expert - authoritative knowledge': 5
})
print(df['Experience'].value_counts())
print(df['SepsisExpertise'].value_counts())

Experience
5    178
4     39
3     10
1      1
Name: count, dtype: int64
SepsisExpertise
4    105
5    105
3     18
Name: count, dtype: int64

/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/1565172145.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Experience'] = df['Experience'].replace({
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/1565172145.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['SepsisExpertise'] = df['SepsisExpertise'].replace({

In [8]:
# exclude_flags = (df['clinical_time'] == 'None') | (df['Duration (min)'] <= 5)
# print(exclude_flags.sum(), "to exclude")
# df = df[~exclude_flags]

In [9]:
df.columns.tolist()

['StartDate',
 'EndDate',
 'Status',
 'IPAddress',
 'Progress',
 'Duration (in seconds)',
 'Finished',
 'RecordedDate',
 'ResponseId',
 'RecipientLastName',
 'RecipientFirstName',
 'RecipientEmail',
 'ExternalReference',
 'LocationLatitude',
 'LocationLongitude',
 'DistributionChannel',
 'UserLanguage',
 'Q_RecaptchaScore',
 'Q_DuplicateRespondent',
 'Q_BallotBoxStuffing',
 'Experience',
 'SepsisExpertise',
 'Q5.1_First Click',
 'Q5.1_Last Click',
 'Q5.1_Page Submit',
 'Q5.1_Click Count',
 'Q5.3',
 'Q5.4',
 'Q5.5',
 'Q6.1_First Click',
 'Q6.1_Last Click',
 'Q6.1_Page Submit',
 'Q6.1_Click Count',
 'Q6.3',
 'Q6.4',
 'Q6.5',
 'Q6.7',
 'Q6.8',
 'Q6.8_8_TEXT',
 'Q7.1_First Click',
 'Q7.1_Last Click',
 'Q7.1_Page Submit',
 'Q7.1_Click Count',
 'Q7.3',
 'Q7.4',
 'Q7.5',
 'Q8.1_First Click',
 'Q8.1_Last Click',
 'Q8.1_Page Submit',
 'Q8.1_Click Count',
 'Q8.3',
 'Q8.4',
 'Q8.5',
 'Q8.7',
 'Q8.8',
 'Q8.8_8_TEXT',
 'Q9.1_First Click',
 'Q9.1_Last Click',
 'Q9.1_Page Submit',
 'Q9.1_Click Count',
 'Q9.3',
 'Q9.4',
 'Q9.5',
 'Q10.1_First Click',
 'Q10.1_Last Click',
 'Q10.1_Page Submit',
 'Q10.1_Click Count',
 'Q10.3',
 'Q10.4',
 'Q10.5',
 'Q10.7',
 'Q10.8',
 'Q10.8_8_TEXT',
 'Q11.1_First Click',
 'Q11.1_Last Click',
 'Q11.1_Page Submit',
 'Q11.1_Click Count',
 'Q11.3',
 'Q11.4',
 'Q11.5',
 'Q12.1_First Click',
 'Q12.1_Last Click',
 'Q12.1_Page Submit',
 'Q12.1_Click Count',
 'Q12.3',
 'Q12.4',
 'Q12.5',
 'Q12.7',
 'Q12.8',
 'Q12.8_8_TEXT',
 'Q13.1_First Click',
 'Q13.1_Last Click',
 'Q13.1_Page Submit',
 'Q13.1_Click Count',
 'Q13.3',
 'Q13.4',
 'Q13.5',
 'Q14.1_First Click',
 'Q14.1_Last Click',
 'Q14.1_Page Submit',
 'Q14.1_Click Count',
 'Q14.3',
 'Q14.4',
 'Q14.5',
 'Q14.7',
 'Q14.8',
 'Q14.8_8_TEXT',
 'Q15.1_First Click',
 'Q15.1_Last Click',
 'Q15.1_Page Submit',
 'Q15.1_Click Count',
 'Q15.3',
 'Q15.4',
 'Q15.5',
 'Q16.1_First Click',
 'Q16.1_Last Click',
 'Q16.1_Page Submit',
 'Q16.1_Click Count',
 'Q16.3',
 'Q16.4',
 'Q16.5',
 'Q16.7',
 'Q16.8',
 'Q16.8_8_TEXT',
 'Q17.1',
 'Productivity',
 'Effectiveness',
 'EaseOfUse',
 'HighOutputQuality',
 'WouldUse',
 'UsefulnessFreeText',
 'IdealAIRoleFreeText',
 'FeedbackFreeText',
 'RandomID',
 '__js_ChoiceChangeDeborahFluids',
 '__js_ChoiceChangeDeborahVaso',
 '__js_ChoiceChangeHeatherFluids',
 '__js_ChoiceChangeHeatherVaso',
 '__js_ChoiceChangeEstherFluids',
 '__js_ChoiceChangeEstherVaso',
 '__js_ChoiceChangeRichardFluids',
 '__js_ChoiceChangeRichardVaso',
 '__js_ChoiceChangeMargaretFluids',
 '__js_ChoiceChangeMargaretVaso',
 '__js_ChoiceChangeMikeFluids',
 '__js_ChoiceChangeMikeVaso',
 'AIInterface',
 'TutorialText',
 '__js_ProgressValue',
 '__js_ProgressText',
 'NoAICase',
 'DeborahShown',
 'DeborahNum',
 'HeatherShown',
 'HeatherNum',
 'EstherShown',
 'EstherNum',
 'RichardShown',
 'RichardNum',
 'MargaretShown',
 'MargaretNum',
 'MikeShown',
 'MikeNum',
 'Email',
 'specialty',
 'specialty_10_TEXT',
 'practice_setting',
 'clinical_time',
 'gender',
 'gender_feedback',
 'age',
 'race',
 'hispanic',
 'Source',
 'specialty_7_TEXT',
 'ethnicity',
 'Total Satisfaction']

In [10]:
no_influences = df[[c for c in df.columns if c.endswith(".8")]].apply(lambda x: x.str.contains("did not affect my thinking at all", case=False), axis=0)
df['SelfReportedUnaffected'] = no_influences.sum(axis=1) >= (~pd.isna(no_influences)).sum(axis=1) - 1
df['SelfReportedAffected'] = no_influences.sum(axis=1) == 0
df['SelfReportedUnaffected'].mean(), df['SelfReportedAffected'].mean()

(0.23684210526315788, 0.4780701754385965)

In [11]:
df.assign(Condition=df['AIInterface'])[[
    'ResponseId',
    'AIInterface',
    'specialty',
    'specialty_10_TEXT',
    'practice_setting',
    'clinical_time',
    'gender',
    'age',
    'race',
    'hispanic',
    'specialty_7_TEXT',
    'ethnicity',
    'Duration (in seconds)',
    'Experience',
    'SepsisExpertise',
    'Productivity',
    'Effectiveness',
    'EaseOfUse',
    'HighOutputQuality',
    'WouldUse',
    'Total Satisfaction',
    'SelfReportedUnaffected',
    'SelfReportedAffected',
    'UsefulnessFreeText',
    'IdealAIRoleFreeText',
    'FeedbackFreeText']].to_csv(f"data/cleaned_respondent_level_{analysis_date}.csv", index=False)

## Decision-Level Data

In [12]:
df.columns = [re.sub(r"^Q(5|6|7|8|9|10|11|12|13|14|15|16)\.(.*)$", r"Decision_\2_\1", c) for c in df.columns]
long_df = pd.wide_to_long(
    df,
    ['Decision_1_First Click_', 'Decision_1_Last Click_', 'Decision_1_Page Submit_', 'Decision_1_Click Count_',
         'Decision_3_', 'Decision_4_', 'Decision_5_', 'Decision_7_', 'Decision_8_', 'Decision_8_8_TEXT_'],
    'ResponseId',
    'Case' 
).reset_index()
long_df.head(10)

,ResponseId,Case,AIInterface,DeborahNum,DeborahShown,DistributionChannel,Duration (in seconds),EaseOfUse,Effectiveness,Email,...,Decision_1_First Click_,Decision_1_Last Click_,Decision_1_Page Submit_,Decision_1_Click Count_,Decision_3_,Decision_4_,Decision_5_,Decision_7_,Decision_8_,Decision_8_8_TEXT_
0,R_6RxfhYGfh8jlhJg,5,Recommended Treatment,0,1,email,773.0,5,4,tsuangw@ccf.org,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,R_5jUO17A3YDcW9sl,5,Options to Consider,5,1,email,831.0,3,2,rishikvashisht@yahoo.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,R_6P5X1V9iJ8kyAxx,5,Options to Avoid,0,1,email,154.0,5,5,rezaimd@yahoo.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,R_6dpSgwpnoJJbFiV,5,Options to Consider,2,1,email,246.0,6,6,Arubinmd@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,R_5KcNS6HUy5bmkq6,5,Options to Avoid,4,1,email,940.0,4,3,harold.palevsky@uphs.upenn.edu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,R_1lJRXsqOpUaonTM,5,Recommended Treatment,3,1,email,553.0,7,6,Kachen@mdanderson.org,...,87.773,98.572,98.575,6,Give up to 1 L of IV fluid.,Wean the existing vasopressor.,Somewhat confident,NaN,NaN,NaN
6,R_6si6i6VtEOCwBC1,5,Options to Consider,1,1,email,1189.0,4,3,Bauer.Philippe@mayo.edu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,R_6GwYOIVLUFVNQuD,5,Recommended Treatment,0,1,email,857.0,2,2,jlberkowitz@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,R_1Y7wZBGuUgNF7I5,5,Options to Avoid,5,1,email,936.0,4,2,herman.dyal@gmail.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,R_1DU7Rz35vHWdkLj,5,Options to Avoid,2,1,email,816.0,6,1,gajic.ognjen@mayo.edu,...,95.716,104.711,104.716,4,Give neither IV fluids nor diuretics.,Continue the existing vasopressor.,Somewhat confident,NaN,NaN,NaN

In [13]:
influences = long_df['Decision_8_'].str.split(",").explode().unique()
for c in influences:
    if pd.isna(c): continue
    long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)

long_df['AIInterface'] = long_df['AIInterface'].where(long_df['Case'] % 2 == 0, 'No AI')
long_df['Case'] = ((long_df['Case'] - 5) // 2).replace({
    0: 'Deborah',
    1: 'Heather',
    2: 'Esther',
    3: 'Richard',
    4: 'Margaret',
    5: 'Mike'
})
long_df

/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/2071281912.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  long_df[f'Influence: {c}'] = long_df['Decision_8_'].str.contains(c).fillna(False)

,ResponseId,Case,AIInterface,DeborahNum,DeborahShown,DistributionChannel,Duration (in seconds),EaseOfUse,Effectiveness,Email,...,Influence: Prompted me to assess the patient further,Influence: Prompted me to consider an alternative plan,Influence: I'm not sure,Influence: Helped me decide between alternatives,Influence: Made me more confident in my plan,Influence: Affected my thinking in some other way (please describe):,Influence: Made me second-guess my plan,Influence: Did not affect my thinking at all,Influence: Gave me an initial plan,Influence: Helped me form an initial assessment of the patient
0,R_6RxfhYGfh8jlhJg,Deborah,No AI,0,1,email,773.0,5,4,tsuangw@ccf.org,...,False,False,False,False,False,False,False,False,False,False
1,R_5jUO17A3YDcW9sl,Deborah,No AI,5,1,email,831.0,3,2,rishikvashisht@yahoo.com,...,False,False,False,False,False,False,False,False,False,False
2,R_6P5X1V9iJ8kyAxx,Deborah,No AI,0,1,email,154.0,5,5,rezaimd@yahoo.com,...,False,False,False,False,False,False,False,False,False,False
3,R_6dpSgwpnoJJbFiV,Deborah,No AI,2,1,email,246.0,6,6,Arubinmd@gmail.com,...,False,False,False,False,False,False,False,False,False,False
4,R_5KcNS6HUy5bmkq6,Deborah,No AI,4,1,email,940.0,4,3,harold.palevsky@uphs.upenn.edu,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2731,R_1LbANtwLORsGJH3,Mike,Options to Avoid,2,1,email,1325.0,7,2,NaN,...,False,False,False,False,False,False,False,False,False,False
2732,R_7o6mhqmhzTcqepy,Mike,Recommended Treatment,1,1,email,832.0,4,3,NaN,...,False,False,False,False,False,False,False,False,False,False
2733,R_32bZLFt0SUnMy4y,Mike,Options to Consider,3,1,email,2063.0,6,4,NaN,...,False,False,False,False,False,False,True,False,False,False
2734,R_3zj2hLcEzVQzRV3,Mike,Options to Consider,NaN,NaN,email,1061.0,6,6,NaN,...,False,False,False,True,False,False,False,False,False,False
2735,R_52cH2B3MKL0eRax,Mike,Options to Avoid,7,1,email,83754.0,6,1,NaN,...,False,False,False,False,False,False,False,True,False,False

In [14]:
nums = []
choice_change_fluids = []
choice_change_vaso = []
for i, row in long_df.iterrows():
    nums.append(row[row['Case'] + 'Num'])
    choice_change_fluids.append(row[f"__js_ChoiceChange{row['Case']}Fluids"])
    choice_change_vaso.append(row[f"__js_ChoiceChange{row['Case']}Vaso"])
    
long_df = long_df.assign(CaseNum=nums, ChoiceChangeFluids=choice_change_fluids, ChoiceChangeVaso=choice_change_vaso)
long_df

,ResponseId,Case,AIInterface,DeborahNum,DeborahShown,DistributionChannel,Duration (in seconds),EaseOfUse,Effectiveness,Email,...,Influence: Helped me decide between alternatives,Influence: Made me more confident in my plan,Influence: Affected my thinking in some other way (please describe):,Influence: Made me second-guess my plan,Influence: Did not affect my thinking at all,Influence: Gave me an initial plan,Influence: Helped me form an initial assessment of the patient,CaseNum,ChoiceChangeFluids,ChoiceChangeVaso
0,R_6RxfhYGfh8jlhJg,Deborah,No AI,0,1,email,773.0,5,4,tsuangw@ccf.org,...,False,False,False,False,False,False,False,0,1,1
1,R_5jUO17A3YDcW9sl,Deborah,No AI,5,1,email,831.0,3,2,rishikvashisht@yahoo.com,...,False,False,False,False,False,False,False,5,1,2
2,R_6P5X1V9iJ8kyAxx,Deborah,No AI,0,1,email,154.0,5,5,rezaimd@yahoo.com,...,False,False,False,False,False,False,False,0,1,1
3,R_6dpSgwpnoJJbFiV,Deborah,No AI,2,1,email,246.0,6,6,Arubinmd@gmail.com,...,False,False,False,False,False,False,False,2,1,NaN
4,R_5KcNS6HUy5bmkq6,Deborah,No AI,4,1,email,940.0,4,3,harold.palevsky@uphs.upenn.edu,...,False,False,False,False,False,False,False,4,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2731,R_1LbANtwLORsGJH3,Mike,Options to Avoid,2,1,email,1325.0,7,2,NaN,...,False,False,False,False,False,False,False,NaN,NaN,NaN
2732,R_7o6mhqmhzTcqepy,Mike,Recommended Treatment,1,1,email,832.0,4,3,NaN,...,False,False,False,False,False,False,False,NaN,NaN,NaN
2733,R_32bZLFt0SUnMy4y,Mike,Options to Consider,3,1,email,2063.0,6,4,NaN,...,False,False,False,True,False,False,False,0,1,1
2734,R_3zj2hLcEzVQzRV3,Mike,Options to Consider,NaN,NaN,email,1061.0,6,6,NaN,...,True,False,False,False,False,False,False,1,2,1
2735,R_52cH2B3MKL0eRax,Mike,Options to Avoid,7,1,email,83754.0,6,1,NaN,...,False,False,False,False,True,False,False,5,1,1

In [15]:
long_df = long_df[[
    'ResponseId', 'Case', 'AIInterface', 'CaseNum', 'Decision_1_First Click_',
       'Decision_1_Last Click_', 'Decision_1_Page Submit_',
       'Decision_1_Click Count_', 'Decision_3_', 'Decision_4_', 'Decision_5_',
       'Decision_7_', 'Decision_8_8_TEXT_', 'ChoiceChangeFluids', 'ChoiceChangeVaso'
] + [c for c in long_df.columns if c.startswith("Influence:")]]
long_df = long_df[~pd.isna(long_df['Decision_3_'])]

In [16]:
alt.Chart(long_df).mark_bar().encode(
    alt.X("Decision_1_Page Submit_:Q", bin=alt.Bin(extent=[0, 600], steps=[5, 10, 15])),
    alt.Y("count():Q")
)

alt.Chart(...)

In [18]:
long_df = long_df.rename(columns={
    "Q3.2": "Experience",
    "Q3.3": "SepsisExpertise",
    "Decision_1_First Click_": "First Click Time",
    "Decision_1_Last Click_": "Last Click Time",
    "Decision_1_Page Submit_": "Page Submit Time",
    "Decision_1_Click Count_": "Click Count",
    "Decision_3_": "Fluid",
    "Decision_4_": "Vasopressor",
    "Decision_5_": "Confidence",
    "Decision_7_": "AIQuality",
    "Decision_8_8_TEXT_": "Other Influences",
})

## Add Decision Quality

In [19]:
fluid_terms = {
    'Give neither IV fluids nor diuretics.': 0,
    "Stop diuretics and don't give IV fluids.": 0,
    'Give up to 1 L of IV fluid.': 1,
    'Stop diuretics and give up to 1 L of IV fluid.': 1,
    'Give more than 1 L of IV fluid.': 2,
    'Stop diuretics and give more than 1 L of IV fluid.': 2,
    'Give a diuretic.': 3,
    'Continue the diuretic.': 3
}

vaso_terms = {
    'Do not give vasopressors.': 0,
    'Wean both existing vasopressors.': 0,
    'Wean the existing vasopressor.': 0,
    'Continue the existing vasopressor.': 1,
    'Start a vasopressor.': 1,
    'Wean the secondary vasopressor.': 1, 
    'Add another vasopressor.': 2,
    'Continue both vasopressors.': 2,
    'Start multiple vasopressors.': 2,
    'Wean the existing vasopressor ONLY IF I ordered fluid and there is a positive response in less than four hours.': 4,
    'Wean one or both vasopressors ONLY IF I ordered fluid and there is a positive response in less than four hours.': 4,
    'Start a vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.': 3,
    'Add another vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.': 5,
    'Wean the secondary vasopressor now, and wean the other vasopressor ONLY IF I ordered fluid and there is a positive response in less than four hours.': 5,
}
print(set(long_df['Fluid'].unique()) - set(fluid_terms.keys()))
print(set(long_df['Vasopressor'].unique()) - set(vaso_terms.keys()))

fluid_nums = long_df['Fluid'].replace(fluid_terms)
vaso_nums = long_df['Vasopressor'].replace(vaso_terms)

invalid_decision = (vaso_nums >= 3) & ~fluid_nums.isin([1, 2])
print("invalid decision:", invalid_decision.sum())

long_df = long_df[~invalid_decision]
fluid_nums = fluid_nums[~invalid_decision]
vaso_nums = vaso_nums[~invalid_decision]

base_decision_numbers = fluid_nums * 3 + vaso_nums
base_decision_numbers = base_decision_numbers.where(vaso_nums < 3,
                                                    12 + (fluid_nums - 1) + (vaso_nums - 3))
base_decision_numbers = base_decision_numbers.where(vaso_nums < 4,
                                                    12 + (fluid_nums - 1) * 2 + (vaso_nums - 4))
base_decision_numbers += 1
base_decision_numbers.value_counts()

set()
set()
invalid decision: 19

/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/3751363438.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  fluid_nums = long_df['Fluid'].replace(fluid_terms)
/var/folders/gj/cy6x5zxs74j__yh6fwqs72500000gp/T/ipykernel_34144/3751363438.py:32: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  vaso_nums = long_df['Vasopressor'].replace(vaso_terms)

2     398
13    178
11    143
5     135
14     74
3      66
1      48
8      33
12     28
10     21
4      15
15     11
16     10
6       8
9       6
7       5
Name: count, dtype: int64

In [20]:
decision_num_df = pd.concat([long_df, fluid_nums.rename('fluid_num'), vaso_nums.rename('vaso_num'), base_decision_numbers.rename('decision_num')], axis=1)
for num in sorted(decision_num_df['decision_num'].unique()):
    print(num)
    print(decision_num_df[decision_num_df['decision_num'] == num][['Fluid', 'Vasopressor', 'fluid_num', 'vaso_num']].value_counts())

1
Fluid                                     Vasopressor                       fluid_num  vaso_num
Give neither IV fluids nor diuretics.     Do not give vasopressors.         0          0           21
                                          Wean the existing vasopressor.    0          0           16
Stop diuretics and don't give IV fluids.  Do not give vasopressors.         0          0            7
Give neither IV fluids nor diuretics.     Wean both existing vasopressors.  0          0            4
Name: count, dtype: int64
2
Fluid                                     Vasopressor                         fluid_num  vaso_num
Give neither IV fluids nor diuretics.     Start a vasopressor.                0          1           243
Stop diuretics and don't give IV fluids.  Start a vasopressor.                0          1            70
Give neither IV fluids nor diuretics.     Continue the existing vasopressor.  0          1            48
                                          Wean the secondary vasopressor.     0          1            37
Name: count, dtype: int64
3
Fluid                                  Vasopressor                   fluid_num  vaso_num
Give neither IV fluids nor diuretics.  Continue both vasopressors.   0          2           43
                                       Add another vasopressor.      0          2           22
                                       Start multiple vasopressors.  0          2            1
Name: count, dtype: int64
4
Fluid                                           Vasopressor                     fluid_num  vaso_num
Give up to 1 L of IV fluid.                     Do not give vasopressors.       1          0           9
                                                Wean the existing vasopressor.  1          0           5
Stop diuretics and give up to 1 L of IV fluid.  Do not give vasopressors.       1          0           1
Name: count, dtype: int64
5
Fluid                                           Vasopressor                         fluid_num  vaso_num
Give up to 1 L of IV fluid.                     Start a vasopressor.                1          1           95
                                                Continue the existing vasopressor.  1          1           22
Stop diuretics and give up to 1 L of IV fluid.  Start a vasopressor.                1          1           14
Give up to 1 L of IV fluid.                     Wean the secondary vasopressor.     1          1            4
Name: count, dtype: int64
6
Fluid                        Vasopressor               fluid_num  vaso_num
Give up to 1 L of IV fluid.  Add another vasopressor.  1          2           8
Name: count, dtype: int64
7
Fluid                            Vasopressor                     fluid_num  vaso_num
Give more than 1 L of IV fluid.  Do not give vasopressors.       2          0           4
                                 Wean the existing vasopressor.  2          0           1
Name: count, dtype: int64
8
Fluid                                               Vasopressor                         fluid_num  vaso_num
Give more than 1 L of IV fluid.                     Start a vasopressor.                2          1           25
                                                    Continue the existing vasopressor.  2          1            4
Stop diuretics and give more than 1 L of IV fluid.  Start a vasopressor.                2          1            3
Give more than 1 L of IV fluid.                     Wean the secondary vasopressor.     2          1            1
Name: count, dtype: int64
9
Fluid                                               Vasopressor                   fluid_num  vaso_num
Give more than 1 L of IV fluid.                     Add another vasopressor.      2          2           3
                                                    Continue both vasopressors.   2          2           1
                                                    Start multiple vasopressors.  2          2           1
Stop diuretics and give more than 1 L of IV fluid.  Start multiple vasopressors.  2          2           1
Name: count, dtype: int64
10
Fluid                   Vasopressor                       fluid_num  vaso_num
Give a diuretic.        Wean both existing vasopressors.  3          0           8
Continue the diuretic.  Do not give vasopressors.         3          0           7
Give a diuretic.        Do not give vasopressors.         3          0           4
                        Wean the existing vasopressor.    3          0           2
Name: count, dtype: int64
11
Fluid                   Vasopressor                         fluid_num  vaso_num
Give a diuretic.        Wean the secondary vasopressor.     3          1           64
Continue the diuretic.  Start a vasopressor.                3          1           38
Give a diuretic.        Start a vasopressor.                3          1           37
                        Continue the existing vasopressor.  3          1            4
Name: count, dtype: int64
12
Fluid                   Vasopressor                   fluid_num  vaso_num
Give a diuretic.        Continue both vasopressors.   3          2           26
Continue the diuretic.  Start multiple vasopressors.  3          2            1
Give a diuretic.        Add another vasopressor.      3          2            1
Name: count, dtype: int64
13
Fluid                                           Vasopressor                                                                                                      fluid_num  vaso_num
Give up to 1 L of IV fluid.                     Start a vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.           1          3           103
Stop diuretics and give up to 1 L of IV fluid.  Start a vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.           1          3            41
Give up to 1 L of IV fluid.                     Wean the existing vasopressor ONLY IF I ordered fluid and there is a positive response in less than four hours.  1          4            29
                                                Wean one or both vasopressors ONLY IF I ordered fluid and there is a positive response in less than four hours.  1          4             5
Name: count, dtype: int64
14
Fluid                                               Vasopressor                                                                                                                                           fluid_num  vaso_num
Give more than 1 L of IV fluid.                     Start a vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.                                                2          3           49
Give up to 1 L of IV fluid.                         Add another vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.                                            1          5           12
Stop diuretics and give more than 1 L of IV fluid.  Start a vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.                                                2          3           11
Give up to 1 L of IV fluid.                         Wean the secondary vasopressor now, and wean the other vasopressor ONLY IF I ordered fluid and there is a positive response in less than four hours.  1          5            2
Name: count, dtype: int64
15
Fluid                            Vasopressor                                                                                                      fluid_num  vaso_num
Give more than 1 L of IV fluid.  Wean the existing vasopressor ONLY IF I ordered fluid and there is a positive response in less than four hours.  2          4           11
Name: count, dtype: int64
16
Fluid                            Vasopressor                                                                                                 fluid_num  vaso_num
Give more than 1 L of IV fluid.  Add another vasopressor ONLY IF I ordered fluid and there is NO positive response in less than four hours.  2          5           10
Name: count, dtype: int64

In [21]:
quality_df = pd.read_csv("../../expert_panel/quality_ratings.csv").rename(columns={
    'Final': 'QualityScore',
    'E1': 'QualityScore_E1',
    'E2': 'QualityScore_E2',
    'E3': 'QualityScore_E3',
    'E4': 'QualityScore_E4',
    'E5': 'QualityScore_E5',
})

In [22]:
scored_df = pd.merge(decision_num_df, quality_df, how='left', left_on=['Case', 'decision_num'], right_on=['Case', 'Decision']).drop(columns=['Decision'])
scored_df

,ResponseId,Case,AIInterface,CaseNum,First Click Time,Last Click Time,Page Submit Time,Click Count,Fluid,Vasopressor,...,Influence: Helped me form an initial assessment of the patient,fluid_num,vaso_num,decision_num,QualityScore_E1,QualityScore_E2,QualityScore_E3,QualityScore_E4,QualityScore_E5,QualityScore
0,R_1lJRXsqOpUaonTM,Deborah,No AI,3,87.773,98.572,98.575,6,Give up to 1 L of IV fluid.,Wean the existing vasopressor.,...,False,1,0,4,2,4,4,5,3,4
1,R_1DU7Rz35vHWdkLj,Deborah,No AI,2,95.716,104.711,104.716,4,Give neither IV fluids nor diuretics.,Continue the existing vasopressor.,...,False,0,1,2,4,7,3,2,7,4
2,R_6q509aZS2abtXbd,Deborah,No AI,3,79.675,87.921,87.928,4,Give up to 1 L of IV fluid.,Add another vasopressor ONLY IF I ordered flui...,...,False,1,5,14,6,6,4,3,4,4
3,R_6Wrg2o8DQo2FsjL,Deborah,No AI,0,23.235,43.681,43.694,4,Give up to 1 L of IV fluid.,Wean the existing vasopressor.,...,False,1,0,4,2,4,4,5,3,4
4,R_65Yj36eVkr1xSKZ,Deborah,No AI,1,22.559,108.769,108.784,15,Give up to 1 L of IV fluid.,Add another vasopressor ONLY IF I ordered flui...,...,False,1,5,14,6,6,4,3,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1174,R_3gZieJvrRzDGHCN,Mike,Options to Consider,1,168.603,180.971,180.979,4,Give neither IV fluids nor diuretics.,Start a vasopressor.,...,True,0,1,2,5,6,6,6,6,6
1175,R_7SdWLi0O3s3mFJz,Mike,Recommended Treatment,2,4.473,603.355,603.363,14,Give up to 1 L of IV fluid.,Start a vasopressor ONLY IF I ordered fluid an...,...,False,1,3,13,7,5,5,5,4,5
1176,R_32bZLFt0SUnMy4y,Mike,Options to Consider,0,39.706,131.113,131.131,5,Give up to 1 L of IV fluid.,Start a vasopressor.,...,False,1,1,5,7,6,5,6,5,6
1177,R_3zj2hLcEzVQzRV3,Mike,Options to Consider,1,27.718,182.456,182.476,8,Give a diuretic.,Start a vasopressor.,...,False,3,1,11,4,3,5,5,3,4
1178,R_52cH2B3MKL0eRax,Mike,Options to Avoid,5,11.519,49.504,49.508,12,Give neither IV fluids nor diuretics.,Start a vasopressor.,...,False,0,1,2,5,6,6,6,6,6

In [25]:
scored_df['First Click Time'] = scored_df['First Click Time'].astype(float)
scored_df['Last Click Time'] = scored_df['Last Click Time'].astype(float)
scored_df['Page Submit Time'] = scored_df['Page Submit Time'].astype(float)

scored_df['TimeSpent'] = scored_df['Page Submit Time']
scored_df['LongTime'] = scored_df['Page Submit Time'] >= 120 # scored_df['Page Submit Time'].median()

scored_df['InfluenceGroupAssessment'] = scored_df[['Influence: Prompted me to assess the patient further',
                                              'Influence: Helped me form an initial assessment of the patient']].any(axis=1)
scored_df['InfluenceGroupPlansConsidered'] = scored_df[['Influence: Gave me an initial plan',
                                                   'Influence: Prompted me to consider an alternative plan']].any(axis=1)
scored_df['InfluenceGroupPlansEvaluated'] = scored_df[['Influence: Helped me decide between alternatives']].any(axis=1)
scored_df['InfluenceGroupConfidence'] = scored_df[['Influence: Made me more confident in my plan',
                                                    'Influence: Made me second-guess my plan']].any(axis=1)
influence_columns = ['Influence: Prompted me to assess the patient further',
 'Influence: Prompted me to consider an alternative plan',
 "Influence: I'm not sure",
 'Influence: Made me more confident in my plan',
 'Influence: Affected my thinking in some other way (please describe):',
 'Influence: Made me second-guess my plan',
 'Influence: Did not affect my thinking at all',
 'Influence: Gave me an initial plan',
 'Influence: Helped me decide between alternatives',
 'Influence: Helped me form an initial assessment of the patient']
short_names = [
    'InfluenceAssessFurther',
    'InfluenceConsiderAlternative',
    "InfluenceImNotSure",
    'InfluenceMoreConfident',
    'InfluenceOther',
    'InfluenceSecondGuess',
    'InfluenceNoEffect',
    'InfluenceInitialPlan',
    'InfluenceHelpDecide',
    'InfluenceInitialAssessment'
]
scored_df = scored_df.rename(columns=dict(zip(influence_columns, short_names)))

In [27]:
scored_df.to_csv(f"data/cleaned_decision_level_{analysis_date}.csv", index=False)

## AI Agreement Data

In [145]:
# Look at the agreement with the various AI interface outputs
ai_quality = pd.read_csv('../../expert_panel/AI_plans_labeled_separate.csv').rename(columns={
    'patient_name': 'Case',
    'ai_condition': 'AI Label'
})
ai_quality['AI Label'] = ai_quality['AI Label'].replace(condition_name_mapping)

In [147]:
# Define pairs of decisions considered "similar" for measuring partial concordance.
# Partial concordance means either the fluid or the vasopressor decision is identical
# to the AI, and the other decision is "similar" to the AI.
vaso_similar_decision = {
    "Deborah": { (0, 1), (0, 4), (2, 5), (1, 2) },
    "Heather": { (0, 1), (1, 3), (1, 2), (0, 3), },
    "Esther": { (0, 1), (1, 3), (1, 2), (0, 3) },
    "Richard": { (0, 1), (1, 2), (1, 4), (0, 4), (1, 5), (0, 5), },
    "Margaret": { (0, 1), (1, 3), (1, 2), (0, 3) },
    "Mike": { (0, 1), (1, 3), (1, 2), (0, 3) }
}

fluid_similar_decision = {
    "Deborah": { (0, 1), (0, 3), (1, 2) },
    "Heather": { (0, 1), (0, 3), (1, 2) },
    "Esther": { (0, 1), (0, 3), (1, 2) },
    "Richard": { (0, 1), (0, 3), (1, 2) },
    "Margaret": { (0, 1), (0, 3), (1, 2) },
    "Mike": { (0, 1), (0, 3), (1, 2) },
}

concordances = []
for i, row in scored_df.iterrows():
    case_name = row["Case"]
    ai_labels = [row['AIInterface']] if row['AIInterface'] != 'No AI' else scored_df['AIInterface'].unique()
    for ai in ai_labels:
        if (ai_quality['AI Label'] == ai).sum() == 0: continue
        ai_fluid_nums = ai_quality[(ai_quality['AI Label'] == ai) & (ai_quality['Case'] == case_name)]['fluid_num'].values.tolist()
        ai_vaso_nums = ai_quality[(ai_quality['AI Label'] == ai) & (ai_quality['Case'] == case_name)]['vaso_num'].values.tolist()
        ai_decision_nums = ai_quality[(ai_quality['AI Label'] == ai) & (ai_quality['Case'] == case_name)]['decision_num'].values.tolist()
        ai_quality_scores = ai_quality[(ai_quality['AI Label'] == ai) & (ai_quality['Case'] == case_name)]['quality'].values.tolist()
        tx_rec_scores = ai_quality[(ai_quality['AI Label'] == 'Recommended Treatment') & (ai_quality['Case'] == case_name)]['quality'].values.tolist()

        if ai == 'Options to Avoid':
            concord = row['decision_num'] not in ai_decision_nums
            partial_concord = any(
                (row['fluid_num'] == fluid_num
                    and row['vaso_num'] != vaso_num
                    ) or
                (row['vaso_num'] == vaso_num
                    and row['fluid_num'] != fluid_num
                    )
                for fluid_num, vaso_num in zip(ai_fluid_nums, ai_vaso_nums)
            )
            
            concordance_type = ('X' if row['decision_num'] in ai_decision_nums else ('Partial' if partial_concord else 'Full'))
        else:
            concord = row['decision_num'] in ai_decision_nums
            partial_concord = any(
                (row['fluid_num'] == fluid_num
                    and (row['vaso_num'] == vaso_num or
                        (vaso_num, row['vaso_num']) in vaso_similar_decision[case_name] or
                            (row['vaso_num'], vaso_num) in vaso_similar_decision[case_name])
                    ) or
                (row['vaso_num'] == vaso_num
                    and (row['fluid_num'] == fluid_num or
                        (fluid_num, row['fluid_num']) in fluid_similar_decision[case_name] or
                            (row['fluid_num'], fluid_num) in fluid_similar_decision[case_name])
                    )
                for fluid_num, vaso_num in zip(ai_fluid_nums, ai_vaso_nums)
            )
            
            concordance_type = ('Full' if concord else ('Partial' if partial_concord else 'X'))
        
        result = {
            **row,
            'HasAI': row["AIInterface"] != 'No AI',
            'AgreementWith': ai,
            'FullConcordance': concord, # concordance_type == 'Full',
            'PartialConcordance': partial_concord, # concordance_type == 'Partial',
            'ConcordanceType': concordance_type,
            'BlindAgreement': row['AIInterface'] != 'No AI' and concord and row['Page Submit Time'] <= 120,
            'SimulatedQualityScore': row['SimulatedQualityScore']
        }
        concordances.append(result)

ai_concordance_df = pd.DataFrame(concordances)

In [148]:
column_order = [
    'ResponseId',
    'Case',
    'AgreementWith',
    'HasAI',
    'AIInterface',
    'FullConcordance',
    'PartialConcordance',
    'ConcordanceType'
]
column_order += [c for c in ai_concordance_df.columns if c not in column_order]

for ai in ai_concordance_df['AgreementWith'].unique():
    ai_concordance_df[ai_concordance_df['AgreementWith'] == ai][column_order].to_csv(f"data/agreement_with_{ai}_{analysis_date}.csv", index=False)
    
ai_concordance_df[ai_concordance_df['HasAI'] == True][column_order].to_csv(f"data/agreement_all_ai_{analysis_date}.csv", index=False)

In [108]:
# Get individual dfs with an overall "agreer" score
for condition in ai_concordance_df['AgreementWith'].unique():
    agreer_flags = ai_concordance_df[ai_concordance_df['AIInterface'] == condition].groupby('ResponseId').agg({'FullConcordance': lambda g: g.sum() >= 0.5}).rename(columns={'FullConcordance': 'HighConcordance'}).reset_index()
    # agreer_flags['HighConcordance'] = agreer_flags['HighConcordance'] > 0.5 # agreer_flags['HighConcordance'].median() - 1e-3
    condition_agreement = pd.merge(agreer_flags, ai_concordance_df.drop_duplicates(['ResponseId', 'Case']), how='left', on='ResponseId')
    print(condition_agreement[['HighConcordance', 'HasAI']].value_counts())
    condition_agreement[condition_agreement['AIInterface'] == 'No AI'][['ResponseId', 'HighConcordance'] + column_order[1:]].to_csv(f"data/agreement_no_ai_{condition}_251204.csv", index=False)

HighConcordance  HasAI
True             True     240
False            True      55
True             False     53
False            False     15
Name: count, dtype: int64
HighConcordance  HasAI
True             True     300
                 False     70
False            True      30
                 False     10
Name: count, dtype: int64
HighConcordance  HasAI
True             True     329
                 False     77
Name: count, dtype: int64

In [109]:
len(condition_agreement['ResponseId'].unique())

79

In [149]:
import re
df = pd.read_csv("data/cleaned_respondent_level_251204.csv")

print(len(df['UsefulnessFreeText'][df['UsefulnessFreeText'].fillna('') != '']), "out of", len(df))
useful_responses = df['UsefulnessFreeText'][df['UsefulnessFreeText'].fillna('') != '']
lengths = useful_responses.apply(lambda r: len(re.split(r'\W+', r)))
print(lengths.median(), lengths.min(), lengths.max())
for ai in df['AIInterface'].unique():
    print(ai)
    print("USEFULNESS\n\n")
    print('\n\n'.join(df[df['AIInterface'] == ai]['UsefulnessFreeText'][df['UsefulnessFreeText'].fillna('') != ''].values.tolist()))
    print("\n\n")
    print("IDEAL ROLE\n\n")
    print('\n\n'.join(df[df['AIInterface'] == ai]['IdealAIRoleFreeText'][df['IdealAIRoleFreeText'].fillna('') != ''].values.tolist()))
    print("\n\n")
    print("MISC\n\n")
    print('\n\n'.join(df[df['AIInterface'] == ai]['FeedbackFreeText'][df['FeedbackFreeText'].fillna('') != ''].values.tolist()))
    print("\n\n")

146 out of 228
25.0 3 291
Recommended Treatment
USEFULNESS


simple direct suggestions

Recommendations were counter to what I have generally been taught regarding sepsis care

Firstly, sorry if I didn't answer the questions correctly about how Sepsis AI influenced me. I said it provided an initial plan largely of I agreed with the plan. I felt that it should be clearer whether or not the AI would re-evaluate the offered plan. The plan did not always seem sufficiently comprehensive. I generally felt more confident in my plan than the AI's plan.

Simplified clinical decisions

useful as it framed the issue, but not useful as some recommendations were not appropriate

Confirmed my plan.

It would help if sepsis AI gave some form of a confidence rating. For example, in the one example, the cirrhotic patient had AKI and one might start vasopressors for concern for HRS but it said no vasopressors. It it had a low confidence on that answer versus a high confidence, one might look at that advice differently

can be used as supplement but still your clinical experience would count more in this critical moment

As with many AI tools, getting a single recommendation based on a complex set of data made me wonder several things in each case
1) What features is the AI looking at.  If it is giving me a response different from my first response, is that because I am missing something in the case, or because it is not considering the same set of data that I am, or is it because in a large data set it can see correlations between data points that lead to a particular outcome that are statistically apparent but don't align with my physiology based linear thinking? In some cases this was a useful prompt to think about things differently, but when I really disagreed it made me wonder if I am completely misinterpreting the data.
2) When a "best" response is given, it makes me wonder about the incremental benefit of the "best" approach vs others.  That is, is the approach only marginally superior in such a way that even a small change in the data or patient condition would suggest a different approach?
3) It would be very helpful to have some idea of what factors the AI is weighting in this scenario that lead to this outcome.  There is always measurement uncertainty or the possibility of rapid change in some of the underlying data in the scenario, and I also really have no understanding of whether the AI is looking at trends over time in the assessment.  I was trained to always ask "what if a single piece of data I have is wrong - would it change my plan significantly" to avoid anchoring and premature closure.  I have no understanding if the AI is robust to those types of concerns.

Not enough information to answer many of the questions - also, for most of them I would do a bedside ultrasound to assess volume status

I may have done this incorrectly but I read what sepsis AI said but did not input info into it.

Sepsis AI was not very useful. It did not take into account the history or the POCUS findings (when available) and that reduced my ability to trust it. Also, some of its recommendations were just off.

Not useful as I don;t know the data it used to reach its recommendations

It made me re-review the cases and consider alternative treatment plans. The decision to give fluids or diuretics (or none) was the treatment choice that I felt was most affected by the use of the AI system. It also made me somewhat more confident in choosing a plan.

It made me spend more time thinking about the patient, since I felt like someone else was watching over me judging my decision.

It was helpful when it confirmed my plan. It did prompt me to rethink it when my plan was different from what it suggested, but I did not change my plan based on what Sepsis AI suggested

While I like the idea of a sepsis AI product, I think having the sepsis AI provide what information it used to come up with this recommendation might be helpful. For example it recommends to not start a vasopressor in someone with a MAP under 60. So if the AI product said “in prior clinic notes the patients outpatient MAPs had been 58 at baseline and using extrapolated data from the 65 trial, we would suggest no vasopressors at this time. Or maybe the opposite (urine output is low, and map is low and outpatient BP readings are high should we target a relatively higher (65) target for map?

I disagreed with all of sepsis AI's recommendations

Didn't feel confident in the recommendations.

consider alternative plan but I would want the reasoning for it.

Would like it to give citations for mgmt recs

Hard to clearly tell what clinical parameters its recommendations are focusing on most strongly.

Discussion of a plan for the “day” is less relevant than for “right now” in ICU care.

. Itemize the findings and support the response with literature

needs to incorporate input from other disease processes (such as cirrhosis-associated AKI, which would specifically benefit from pressor from the perspective of AKI)

it was really hard to assess the accuracy of sepsis AI because so much information was missing from the cases.  For example, it is difficult to assess fluids as I dont know the weight of the patient.  Without a CBC to see if bleeding in some cases, would also be nice.
In essence, the scenarios are too simple and have too much missingness to assess its accuracy

'-It was useful to confirm my initial plans
-I need to understand how the recommendations are generated before applying them to a real patient. There’s a lot of nuances that were not included in the scenarios. For example no patient weights were given, and this is essential to determine if the volume of resuscitation fluid is adequate or not. Another example in one of the scenarios that seemed like ARDS: did sepsis AI recommend diuretics based on the FACT trial for example, to reduce vent days? What if my priority is not that, like in a patient who has evolving AKI or large fluid balance or escalating pressors / borderline MAPs? Less vent days (-2.5 per FACTT) might not be worth pursuing in these scenarios for example and these clinical conditions were not present in that trial population. Will this tool identify and discern all this or just analyze a set of limited variables (oxygenation, hemodynamics, kidney function)?

Would seem to be best for providers with little sepsis management experience.

The feedback is very dichotomous but in real practice things are a bit more stepwise. For instance - plans are always going to be wean vasopressors but the recommendation of giving diuretics while on pressors is not trivial even if the patient is in overload. So yeah, we want to give a diuretic but have to hold the fort and will sometimes give fluid. Essential the AI device is not really capturing the sequence of events by giving a dichotomous plan.

Served as an anchor for decision making - either confirmation of a plan or when the output was not aligned with my plan, caused me to carefully consider/ reconsider my plan.


It seemed like it was very comfortable with things that would give clinicians pause. It would help if it had some data behind it's decisions.

made me re-evaluate the case, and question my decision

Not useful, many of the recommendations did not make sense, based on the clinical scenario.

Gave an initial plan

When Sepsis AI recommends a plan different than I would consider it makes me reassess my assessment and management plan

would be useful to provide more clinical evidence behind the sepsis AI recommendations

it is unclear to me how good Sepsis AI is.  And what is the gold standard here?  Guidelines?

While it seems like a great idea, it felt like the AI was simply regurgitating what future clinical courses turned out best for the patient, without taking into account that those courses are often driven by how the patient's clinical picture evolves outside of our treatment.

it's too simplistic. patient care is dynamic and requires constant bedside assessment including POCUS, hemodynamic assessment, fluid challenges, etc. Sepsis AI needs to incorporate more diagnostic information and asks more questions before it jumps to recommendations

It's unclear to me how dynamic volume assessments would affect the AI assessment

Easy to use, very clear recommendations

There was no explanation why the sepsis AI came to the conclusion. Additionally, no hemodynamic data were present. Bedside echo information was not used. Markers of Perfusion like physical exam findings were not included. The answers are too black and white. There is an art to patient management. Sometimes a brief low dose vasopressor may prevent your patient from having an arrest while intubating but can be weaned later for example.



IDEAL ROLE


provide options, perhaps several recommendations instead of just one

initial plan; or when unclear next steps
also for training and teaching

If it is sufficiently comprehensive and can revise it's evaluation based on changes in clinical status, the AI could offer support for a busy service where changes in patient status may not be immediately reported to me as the provider. Otherwise, it could be used to provide support to less experienced providers.

Even though Sepsis AI found 100 patients our of many thousand who were like my patients, the response to treatment needs to be followed as conditions change, often unpredictably. Single decisions without a follow up plan seems inadequate

minimal until it improves further

Informational.  To drive education.

To aid in making decisions when the data is not clear
To add guardrails to providers with less experience or sepsis knowledge

as supplemental tool but worry about over reliance on it and physician not using their own clinical judgement esp trainees and new physicians

Ideally, AI would not just give me a recommendation, but situate the data extracted from a certain situation within the framework of evidence based or at least guideline based care.  With just a recommendation, I am left doubting my own decision and second guessing myself without a real understanding of where I might differ from the AI decision, which is just frustrating.

Not sure

Try to catch subtle changes that we may miss.

I hope in the future, AI helps me identify phenotypes of sepsis (hyper or hypoinflammatory) and help me identify some treatments I am clearly missing (eg. Using zosyn in someone who has a history of resistance to it).

Supportive most useful with unexperienced clinicians

To give an initial treatment recommendation (it might be nice if it briefly explained how it came to decide on an initial treatment recommendation).

Should prompt things to think about and discuss with others, rather than declare things about what to do. Also it needs to give a rationale, otherwise it will end up being ignored (which happened to me by the end of the cases). Without knowing its rationale, it is worse than useless since it detracts from my productivity and peace of mind.

Dynamic assessments - that is, this patient needs fluid, keep giving fluids, STOP, and start vasopressor now.  Would be useful to see HOW different the outcomes are: for example if there is an 88% vs. 90% chance of mortality or instead a 25% vs. 75% chances of mortality.

Supportive - prompt reconsideration, reduce bias

If AI can be used to assimilate data on diastolic dysfunction, volume resuscitation recieved, baseline vitals and current trends in vitals I think might help providers. In real life the data is changing by minute, and  how often will the AI product update new suggestions?
If a cxr is done once a day, and lags the clinical picture but in the afternoon patient has increased rr and increased O2 requirements the advice might change from rounds earlier in the day, is this captured and how often by the AI product?

May be helpful for an intern or junior level learner who feels out of depth or overwhelmed. Not helpful for an intensivist or experienced senior physician

Has a role, just needs to be "fine tuned".

to consider alternative plans. I disagree with the AI approach .

I do think there is a role. It just would need to address some of the issues above and show itself over time to be reliable rather than feeling like the flip of a coin. Including citations/references would provide greater confidence.

Reminds me a bit of the burn navigator technology for fluid resuscitating burn patients.

Suggestions

training of residents and/or use in initial management of patients with sepsis

Again, I think as above, the question is how the AI will ingest the information, what is automatically extracted from EHR versus have to be put into the UI by the provider.  If the former, what data are extracted.
For example, in the patient with Hypertension, as a provider, I would look for baseline BP, to help tailor the treatment plan, will this do this
In essence, trust in AI requires transparency in what data are being used by the model, without that, this is difficult to asses

'-Early identification
-Continuous analysis of patient trends and automatic recommendations for antibiotics once C&S are available
-Treatment suggestions as in the scenarios, but with clear rationale behind them


None I don’t want to rely on AI to guide my decisions

I think it needs to be a bit more specific in terms of recommendations. What pressor, how much fluid etc.

Unclear yet - would want to have better understanding of its effectiveness.

Helping to refine algorithms some.

could be helpful, its tough though. sepsis is not a one form of disease

Could be helpful, if it integrated more data related to volume status, potential responsiveness.

give Rx options

More detail regarding which data points inform the recommendation. Caution/warning when treatment plan may cause harm or critical value not addressed in timely fashion.

I worry that it may be difficult for sepsis AI to understand trajectories

At the current state, I would use it only as a possible memory aid (i.e. run it to make sure I didn't overlook something). I would not rely on it.

Evidence-based recommendations

Also identify potential sepsis patients where the initial diagnosis is incorrect

give more evidence for your sepsis patient fitting particular categories (ie sepsis in patients with HFrEF and AKI)

Currently not a role. I think AI needs more inputs to be useful including continuous hemodynamic data and perfusion assessments.



MISC


Please see above.

Interesting.  Each clinical scenario, while it has suggested AI data does not seem like it can appreciate the bedside clinical factors that are sometimes confounders.

none

Would like to include POCUS results

Maybe put echo results for PE case to show whether RV overload present.

I wish the study gave me POCUS findings for every case. Especially in the first two cases I would have done POCUS, gotten a history of fluid intake and made decisions on whether to give more fluids or not. Also having repeat CCR findings would have helped in some cases for me to be more confident in my plan.

An interesting app that I think could be useful in critical care - probably a lot of other pathologies that an AI system can be developed to assist with management.

Study is interesting but I do believe that, predictive analytics will have its strongest applications when it opens a conversation between providers about creating rationales, rather than telling them what to do (at least until confidence builds). There is significant literature that says that many physicians ignore AI based recommendations, but I believe that is because the rationale is not available. A simpler use of AI for the time being should be in the workflow automation space rather than clinical decision support.

Does sepsis AI offer plans about starting additional vasopressors, role of steroids, etc?

I think we are all excited to have AI products that allow us to do our jobs better. I am confident that AI will be assisting us especially in the diagnostic realm. In terms of deciding fluid or volume status I remain skeptical. Volume status is the holy grail of critical care medicine, and I’m weary of AI knowing how much volume to give to a patient or when to start a diuretic, when two “expert” clinicians can disagree on the same clinical vignette.

The clinical assessment at the bedside, touch of skin and other factors are not being accounted for in the cases or the sepsis AI recommendations (at least it feels that way). Hard to imagine how it would help change my management.

I want the reason for the intervention.

Helping

Nice effort. Would be interested to follow the progression of this project. Good luck!

When one says wean vasopressors - does this mean if it meets certain criteria such as an acceptable MAP goal? Or based on the current data points - eg MAP is 55 but just turn down the pressors anyway?

It seemed pretty comfortable with low blood pressures. It would help to have a better volume exam on the cases which it doesn't seem like sepsis AI takes into account at all.

Some of the cases are challenging to come up with a clear plan without additional info/bedside evaluation.

This iteration of SepsisAI was oversimplified. Also, having chest X-ray data would help clarify points where a difference in management decisions between myself and AI.

It was unclear with the study if this was a test of Sepsis AI or a test of whether or not clinicians would use sepsis AI.  It would be great to hear more about how sepsis AI was vetted and built.

Perhaps with more variables incorporated and more training it's responses would feel like they were more based on experience than hope that the ideal outcome would occur.

Suggest to add a confidence statement (qualitative or quantitative) in regards to the ai recommendations



Options to Consider
USEFULNESS


Adjust the recommendations to the phases of sepsis following the 'ROSE' algorithm

didn't findit to be too useful - lactate really would help it more

Not really.  The plan did not give any additional insight

Gives options that I would not consider in real life.

it proposed treatment options, but they often seemed on opposite sides of the spectrum (fluids vs diuresis) which i think is conclusion/task focused and skips the pathophysiology assessment of the patient.

I do think it is somewhat helpful. I think it could provide some rationale for the decision making if possible.

It is useless, because unless there is alternative data that it receives that the clinician does not it does not have enough information to make informed decisions regarding pressors, diuretics, and hemodynamic status.
It seems like the recommendations therefore might be based on data from large groups of patients

I was surprised by some of the treatment regimen suggestions. If the answer included references to support the claims that a given regimen was associated with lower mortality, (particularly if it was not what I was originally intending to do), that would make me more likely to believe the AI and more likely to implement the suggestion.



Didn’t fully agree with the output

incorporate more patient data to create better outcomes assessments

It mostly forced me to reassess my initial assumptions - ie. why is it recommending something I would not, and did I miss something.

It would be useful  to see the thinking process behind how the AI came to the decisions so you can cross check it for validity

I'd like to see it reference its recommendations. I would like to know what studies or data points it used in making its decision to understand its logic and ascertain if I agree with the appropriateness of the references to this particular patient.

Therapeutic options that were often paired did not allow for exclusivity of plan trajectories.
